# Generated by Django 3.1.4 on 2020-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20201214_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(max_length=10)),
                ('isbn_13', models.CharField(max_length=13)),
            ],
        ),
    ]
